from salebot_nlu.ic.ulmfitclassifier import ULMFITIntentClassifier
from salebot_nlu.ner.flair_entities_extractor import FlairEntitiesExtractor
from salebot_nlu.ner.regex_entities_extractor import XegexEntityExtractor
from salebot_nlu.joint.onenetnlu import OneNetNLU